### ISSUE TITLE
Add a license to the repository

### ISSUE THREAD

**Issue by cbjuan** [DynamicDevices/does-rpi3-qiskit#1]
I recently came across your project does-rpi3-qiskit and I noticed that the repository github.com/DynamicDevices/does-rpi3-qiskit currently does not have a license specified.

Why Adding a License is Important?

As [GitHub documents](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)
>Public repositories on GitHub are often used to share open source software. For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software.

Would be possible to add a valid license to this repository? Probably something really OpenSource such as the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0) would fit really well.

Thanks!

**Comment by ajlennon** [comment]
Sure - send a PR in and I'll review it

**Comment by ajlennon** [comment]
Merged in - super - thanks for that guys!

**Comment by ajlennon** [comment]
Hi @cbjuan @vabarbosa ....

I've been working on a Quantum Safe encryption repo for Yocto which is here

https://github.com/DynamicDevices/meta-quantum-safe

Now I have the license down as MIT as this is the main license of the OQS project.

However they do state various sub-components of that project are under different licenses and I want to get this all aligned properly.

Given you both seem to have an interest in Quantum and licensing I wondered if you'd be willing to take a quick look and speak with me on best practice? Thanks in advance!

**Comment by vabarbosa** [comment]
hi @ajlennon, i would recommend reviewing https://choosealicense.com/
which may be able to help you figure out what is best for your project

**Comment by ajlennon** [comment]
That's great - thanks for the signposting @vabarbosa
